name: Multi-Stage Pipeline 1

on:
  push:
    branches:
      - main
  pull_request:
    branches:  
      - main 
 

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout Repository
  #     uses: actions/checkout@v2

  #   - name: Set up Java
  #     uses: actions/setup-java@v2
  #     with:
  #       java-version: '11'
  #       distribution: 'adopt'

  #   - name: Build
  #     run: |
  #       mvn clean install
  #       mvn clean package
        
  #   - name: Archive Artifacts
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: java-app
  #       path: target/

  build-and-push:
    runs-on: ubuntu-latest
    #needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: build and push docker images
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
          image: rakshithamayya/servlet-app
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  #   - uses: actions/checkout@v3
  #     name: Check out code

    # - uses: mr-smithers-excellent/docker-build-push@v6
    #   name: Build & push Docker image
    #   with:
    #     image: rakshithamayya/image:latest
    #     tags: v1, latest
    #     registry: docker.io
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v1

    # - name: Build Docker image
    #   run: |
    #     docker buildx create --use
    #     docker build -t my-app:imgv1 .
    #     docker tag my-app:imgv1   docker.io/${{ secrets.DOCKER_USERNAME }}/myapp:v1
    #     docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    #     docker push docker.io/${{ secrets.DOCKER_USERNAME }}/myapp:v1

    #  env:
    #    DOCKER_CLI_ASL: "1"
    
  # docker-build-push:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Download artifact
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: java-app
  #       path: target/

  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v1

  #   - name: Build the Docker image
  #     run: |
  #       docker buildx create --use
  #       docker buildx build -t ${{ secrets.DOCKER_USERNAME }}/your-app:latest .
  #       docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
  #       docker push ${{ secrets.DOCKER_USERNAME }}/your-app:latest
  #     env:
  #       DOCKER_CLI_ASL: "1"


  release:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:

    
 
    #- name: Set up Vault CLI
    #  run: |
    #    VAULT_VERSION="1.8.1"  # Replace with the desired version
    #    curl -fsSL -o vault.zip https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip
    #    unzip vault.zip
    #    sudo mv vault /usr/local/bin/
    #    vault --version  # Check that Vault is installe
  
    #- name: Retrieve secret from Vault
    #  run: |
    #    export VAULT_ADDR=http://127.0.0.1:8200
    #    export VAULT_TOKEN=${{ secrets.VAULT_TOKEN }}
    #    export SECRET_VALUE=$(vault kv get -mount="secret" "MYSECRET")
    #    echo "Secret value: $SECRET_VALUE"
    #    echo "VAULT_SECRET=$SECRET_VALUE" >> $GITHUB_ENV"""



    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
          fetch-depth: 0 

    - name: Set up Git
      run: |
        git config user.email "rakshithamayya6@gmail.com"
        git config user.name "rakshitha-mayya"
        
      

    #- name: Set up Node.js
    #  uses: actions/setup-node@v3
    #  with:
    #    node-version: '14'


    #- name: Install dependencies
    #  run: npm install

    - name: Get Previous tag
      id: previoustag
      uses: 'WyriHaximus/github-action-get-previous-tag@v1'
      env:
        GITHUB_TOKEN: ${{ secrets.NEW_GIT_SECRET }}
          
    - name: Get next version
      id: next
      uses: 'WyriHaximus/github-action-next-release-version@1.0.0'
      with:
        version: ${{ steps.previoustag.outputs.tag }}

    - name: Create release
      id: create_release_id
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.NEW_GIT_SECRET }}
      with:
        tag_name: ${{ steps.next.outputs.version }}
        release_name: Release ${{ steps.next.outputs.version }}   

    #- name: Get current version
    #  id: get_latest_tag
    #  run: |
    #    LATEST_TAG=$(git describe --tags --abbrev=0 --always 2>/dev/null || echo "v0.0.0")
    #    echo "::set-output name=latest_tag::$LATEST_TAG"

    #- name: Increment version
    #  id: bump_version
    #  run: |
    #    LATEST_VERSION=${{ steps.get_latest_tag.outputs.latest_tag }}
    #    IFS='.' read -r -a VERSION_PARTS <<< "$LATEST_VERSION"
    #    ((VERSION_PARTS[${#VERSION_PARTS[@]}-1]++))
    #    NEW_VERSION="${VERSION_PARTS[0]}"
    #    for ((i = 1; i < ${#VERSION_PARTS[@]}; i++)); do
    #      NEW_VERSION="${NEW_VERSION}.${VERSION_PARTS[i]}"
    #    done
    #    echo "::set-output name=new_version::$NEW_VERSION"

    #- name: Bump version and create release
    #  run: |
    #    git tag -a ${{ steps.bump_version.outputs.new_version }} -m "Release ${{ steps.bump_version.outputs.new_version }}"
    #    git push origin ${{ steps.bump_version.outputs.new_version }}
    #    gh release create ${{ steps.bump_version.outputs.new_version }} -t "Release ${{ steps.bump_version.outputs.new_version }}"
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.NEW_GIT_SECRET }}

    #- name: Bump version and create release
    #  run: |
    #    # Update your versioning logic here (if needed)
    #    git tag -a v1.2.3 -m "Release v1.2.3"
    #    git push origin v1.2.3
    #    gh release create v1.2.3 -t "Release v1.2.3"
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.NEW_GIT_SECRET }}

  deploy_dev:
    runs-on: ubuntu-latest
    environment: 'dev'
    needs: release

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: java-app
        path: target/

    - name: Deploy to Dev
      run: echo "Deploying to Dev environment"

  deploy_qa:
    runs-on: ubuntu-latest
    environment: 'QA'
    needs: deploy_dev

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: java-app
        path: target/

    - name: Deploy to QA
      run: echo "Deploying to QA environment"

  deploy_prod:
    runs-on: ubuntu-latest
    environment: 'Prod'
    needs: deploy_qa

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: java-app
        path: target/

    - name: Deploy to Prod
      run: echo "Deploying to Prod environment"

  #push_to_dockerhub:
  #  runs-on: ubuntu-latest

  #  steps:
  #  - name: Checkout code
  #    uses: actions/checkout@v2

  #  - name: Set up Docker Buildx
  #    uses: docker/setup-buildx-action@v1

  #  - name: Build the Docker image
  #    run: docker build -t ${{ secrets.DOCKER_USERNAME }}/java-app:latest .

  #  - name: Log in to Docker Hub
  #    run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

  #  - name: Push the Docker image to Docker Hub
  #    run: docker push ${{ secrets.DOCKER_USERNAME }}/java-app:latest

 
 